version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '08:00'
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    cooldown:
      default-days: 1
    groups:
      actions-minor-patch:
        update-types:
          - patch
          - minor
      actions-major:
        update-types:
          - major
