name: brew test-bot

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test-bot:
    runs-on: ubuntu-latest
    container: ghcr.io/homebrew/brew:main

    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@1f8e202ffddf94def7f42f6fa3a482e821489f9c # 2026.07.10.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@v6
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: linux-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: linux-rubygems-

      - run: brew test-bot --only-cleanup-before
      - run: brew test-bot --only-setup
      - run: brew test-bot --only-tap-syntax
      - run: brew test-bot --only-formulae
        if: github.event_name == 'pull_request'

